services:
  postfix:
    image: postfix-relay
    container_name: postfix-relay
    environment:
      RELAY_HOST: smtp.gmail.com #replace it with your relay host
      RELAY_PORT: 587
      MYHOSTNAME: mydomain.com
      MYNETWORKS: "127.0.0.0/8 192.168.0.0/16"  #Adjust to your network
      SASL_PASSWD: "user@domain.com:yourpassword" 
    #volumes:
    #  - ./postfix-spool:/var/spool/postfix
    ports:
      - "25:25"
    restart: always
