services:
  postfix:
    image: postfix-relay
    container_name: postfix-relay
    environment:
      RELAY_HOST: smtp.gmail.com
      RELAY_PORT: 587
      MYHOSTNAME: mydomain.com
      MYNETWORKS: "127.0.0.0/8 192.168.0.0/16 172.17.0.0/16"
      SASL_PASSWD: "${SMTP_USER}:${SMTP_PASS}"
    env_file:
      - .env
    #volumes:
    #  - ./postfix-spool:/var/spool/postfix
    ports:
      - "25:25"
    restart: always
